version: '3.8'

services:
  grpc_service:
    build:
      context: ./grpc_service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./grpc_service:/app
    command: poetry run python main.py

  graphql_service:
    build:
      context: ./graphql_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./graphql_service:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  rest_service:
    build:
      context: ./rest_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./rest_service:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    # No es necesario un puerto si solo se usa para ejecutar scripts de prueba
    # command: poetry run python client.py # Esto se ejecutará manualmente desde el notebook