# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nml_service\"\x19\n\x07\x46\x65\x61ture\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1e\n\nPrediction\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x32\x43\n\tMLService\x12\x36\n\x07Predict\x12\x13.ml_service.Feature\x1a\x16.ml_service.Predictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATURE']._serialized_start=32
  _globals['_FEATURE']._serialized_end=57
  _globals['_PREDICTION']._serialized_start=59
  _globals['_PREDICTION']._serialized_end=89
  _globals['_MLSERVICE']._serialized_start=91
  _globals['_MLSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
